version: '3.8'

services:
    db:
        image: mariadb:10.7.3
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: good-food-db
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""

    fpm:
        depends_on:
            - db
        build:
            context: .
        volumes:
            - ./:/var/www:cached
        ports:
            - "8000:8000"
        command: "php artisan serve --host=0.0.0.0 --port=8000"
#    command: "php -S 0.0.0.0:8000 -t public"
