# fly.toml app configuration file generated for good-food-back on 2023-07-05T13:28:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "good-food-back"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.0"

[env]
  APP_DEBUG = "false"
  APP_ENV = "production"
  APP_NAME = "Good Food"
  APP_URL = "http://localhost/"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "tls"
  MAIL_FROM_ADDRESS = "contact@goodfood.com"
  MAIL_FROM_NAME = "${APP_NAME}"
  MAIL_HOST = "smtp.mailtrap.io"
  MAIL_MAILER = "smtp"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
