# fly.toml file generated for good-food-back on 2022-11-18T15:12:47+01:00

app = "good-food-back"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.0"

[env]
  APP_DEBUG = "false"
  APP_ENV = "production"
  APP_KEY = "base64:KWBdFNthxn86sKPJ9dWr8KRn1IuNbvyNgsy0enwwkDw="
  APP_NAME = "Good Food"
  APP_URL = "http://localhost/"
  DB_CONNECTION = "mysql"
  DB_DATABASE = "good-food"
  DB_HOST = "aws-eu-west-2.connect.psdb.cloud"
  DB_PASSWORD = "pscale_pw_GkF8H2EXZFynuoaBVp5wA3Qt0pPO9X0aSQMPc3enLwx"
  DB_PORT = "3306"
  DB_USERNAME = "gnqdrrulhlcen86xvf60"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "tls"
  MAIL_FROM_ADDRESS = "contact@goodfood.com"
  MAIL_FROM_NAME = "${APP_NAME}"
  MAIL_HOST = "smtp.mailtrap.io"
  MAIL_MAILER = "smtp"
  MAIL_PASSWORD = "5531d0d52cd1aa"
  MAIL_PORT = "2525"
  MAIL_USERNAME = "2c12fb8fe83082"
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
